import type { Metadata } from 'next';
import Client from './client';

// Demo landing pages are AI-generated previews for individual leads — useful to
// the recipient but not content we want indexed.
export const metadata: Metadata = {
  title: 'Website Demo — Cold Scout',
  description: 'A preview website generated by Cold Scout.',
  robots: { index: false, follow: true },
};

export const revalidate = 1800;

export default function Page() {
  return <Client />;
}
