/**
 * Single source of truth for pricing across JSX, JSON-LD, llms.txt, the OSS
 * README, and the OG image generator.
 *
 * `BASE_PRICING` is the authoritative INR price (Razorpay processes in INR).
 * `CURRENCIES` is presentation-only — what we display when the visitor's
 * region is detected. Updating BASE_PRICING here flows through to:
 *   - <Pricing /> page comparison cards
 *   - JSON-LD Service / Offer schemas
 *   - SoftwareApplication offers in index.html
 *   - llms.txt (regenerated by scripts/generate-llms.ts)
 *   - sitemap.xml (regenerated by scripts/generate-sitemap.ts)
 */

export type PlanKey = 'oss' | 'pro' | 'enterprise';

export interface Plan {
  key: PlanKey;
  name: string;
  /** INR per month. 0 = free / self-host. */
  inrPerMonth: number;
  /** One-line value-prop used in JSON-LD `description`. */
  shortDescription: string;
  /** URL the offer points at (deeplink, signup, GitHub releases, mailto). */
  offerUrl: string;
  /** Bullet features in display order. */
  features: string[];
}

export const BASE_PRICING: Record<PlanKey, Plan> = {
  oss: {
    key: 'oss',
    name: 'Open Source',
    inrPerMonth: 0,
    shortDescription:
      'Self-hosted, full platform access with unlimited leads using your own API keys.',
    offerUrl: 'https://github.com/colddsam/coldscout/releases',
    features: [
      'Full platform access',
      'All 5 pipeline stages',
      'Unlimited leads (your API keys)',
      'Web dashboard included',
      'Community support (GitHub Issues)',
      'Docker & pip install ready',
    ],
  },
  pro: {
    key: 'pro',
    name: 'Pro',
    inrPerMonth: 100,
    shortDescription:
      'Managed API and MCP server access with 2,000 leads per month, AI qualification, and email support.',
    offerUrl: 'https://coldscout.colddsam.com/pricing',
    features: [
      'No deployment needed',
      'MCP server access',
      '2,000 leads/month',
      'AI qualification + email generation',
      'Dashboard analytics',
      'Email support (48h response)',
      '99.5% uptime SLA',
    ],
  },
  enterprise: {
    key: 'enterprise',
    name: 'Enterprise',
    inrPerMonth: 2000,
    shortDescription:
      'Dedicated infrastructure, unlimited leads, custom ICP model training, white-label templates, and priority 4-hour support SLA.',
    offerUrl: 'mailto:colddsam@gmail.com?subject=Cold%20Scout%20Enterprise%20Inquiry',
    features: [
      'Unlimited leads',
      'Dedicated API instance',
      'Custom ICP model training',
      'White-label email templates',
      'Priority support (4h response)',
      'Custom integrations',
      'Dedicated account manager',
    ],
  },
} as const;

export const PLANS: readonly Plan[] = [BASE_PRICING.oss, BASE_PRICING.pro, BASE_PRICING.enterprise];

/**
 * Display-only currency conversions for the regional selector.
 * Razorpay processes the INR value above. Keep this list in sync with the UI
 * dropdown — do not let the numbers drift apart from the multiplier each
 * currency implies, since visitors will compare them.
 */
export interface CurrencyDisplay {
  code: string;
  symbol: string;
  flag: string;
  /** Display price for the Pro plan in this currency. */
  pro: number;
  /** Display price for the Enterprise plan in this currency. */
  enterprise: number;
}

export const CURRENCIES: CurrencyDisplay[] = [
  { code: 'USD', symbol: '$', flag: '🇺🇸', pro: 1, enterprise: 24 },
  { code: 'EUR', symbol: '€', flag: '🇪🇺', pro: 1, enterprise: 22 },
  { code: 'GBP', symbol: '£', flag: '🇬🇧', pro: 1, enterprise: 19 },
  { code: 'INR', symbol: '₹', flag: '🇮🇳', pro: 100, enterprise: 2000 },
  { code: 'CAD', symbol: 'C$', flag: '🇨🇦', pro: 2, enterprise: 33 },
  { code: 'AUD', symbol: 'A$', flag: '🇦🇺', pro: 2, enterprise: 36 },
  { code: 'JPY', symbol: '¥', flag: '🇯🇵', pro: 175, enterprise: 3500 },
  { code: 'BRL', symbol: 'R$', flag: '🇧🇷', pro: 6, enterprise: 118 },
];

export function formatPriceLabel(plan: Plan): string {
  if (plan.inrPerMonth === 0) return 'Free';
  return `₹${plan.inrPerMonth.toLocaleString()}`;
}
