"""Add LeadSocialNetwork table

Revision ID: 4bc63e0465f2
Revises: 95ce86b637d4
Create Date: 2026-03-01 23:57:38.887758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bc63e0465f2'
down_revision: Union[str, None] = '95ce86b637d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_social_networks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['public.leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_lead_social_networks_lead_id'), 'lead_social_networks', ['lead_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lead_social_networks_platform_name'), 'lead_social_networks', ['platform_name'], unique=False, schema='public')
    op.drop_constraint('email_events_lead_id_fkey', 'email_events', type_='foreignkey')
    op.drop_constraint('email_events_outreach_id_fkey', 'email_events', type_='foreignkey')
    op.create_foreign_key(None, 'email_events', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'email_events', 'email_outreach', ['outreach_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('email_outreach_lead_id_fkey', 'email_outreach', type_='foreignkey')
    op.drop_constraint('email_outreach_campaign_id_fkey', 'email_outreach', type_='foreignkey')
    op.create_foreign_key(None, 'email_outreach', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'email_outreach', 'campaigns', ['campaign_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('leads', 'first_opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of first email open.',
               existing_comment='Records the exact timestamp when the lead first opened an outreach email sent by your system. This is a key metric for tracking engagement and email deliverability.',
               existing_nullable=True)
    op.alter_column('leads', 'first_clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of first link click.',
               existing_comment='Records the exact timestamp when the lead first clicked on any link contained within one of the outreach emails. This indicates a higher level of interest or engagement compared to just opening the email.',
               existing_nullable=True)
    op.alter_column('leads', 'raw_places_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Raw external API payload for discovery fallback.',
               existing_comment="Stores the raw, unprocessed JSON payload returned from the external API (like Google Places API) during the discovery phase. Keeping the raw data ensures that you have access to all the original information about the business, even if some of it isn't mapped to specific columns in your database.",
               existing_nullable=True)
    op.alter_column('leads', 'notes',
               existing_type=sa.TEXT(),
               comment='Custom context or remarks about the lead.',
               existing_comment="A general-purpose text field where users or the system can store manual remarks, custom observations, or any extra context about the lead that doesn't fit into the structured columns.",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'notes',
               existing_type=sa.TEXT(),
               comment="A general-purpose text field where users or the system can store manual remarks, custom observations, or any extra context about the lead that doesn't fit into the structured columns.",
               existing_comment='Custom context or remarks about the lead.',
               existing_nullable=True)
    op.alter_column('leads', 'raw_places_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="Stores the raw, unprocessed JSON payload returned from the external API (like Google Places API) during the discovery phase. Keeping the raw data ensures that you have access to all the original information about the business, even if some of it isn't mapped to specific columns in your database.",
               existing_comment='Raw external API payload for discovery fallback.',
               existing_nullable=True)
    op.alter_column('leads', 'first_clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Records the exact timestamp when the lead first clicked on any link contained within one of the outreach emails. This indicates a higher level of interest or engagement compared to just opening the email.',
               existing_comment='Timestamp of first link click.',
               existing_nullable=True)
    op.alter_column('leads', 'first_opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Records the exact timestamp when the lead first opened an outreach email sent by your system. This is a key metric for tracking engagement and email deliverability.',
               existing_comment='Timestamp of first email open.',
               existing_nullable=True)
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.create_foreign_key('email_outreach_campaign_id_fkey', 'email_outreach', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key('email_outreach_lead_id_fkey', 'email_outreach', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.create_foreign_key('email_events_outreach_id_fkey', 'email_events', 'email_outreach', ['outreach_id'], ['id'])
    op.create_foreign_key('email_events_lead_id_fkey', 'email_events', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_public_lead_social_networks_platform_name'), table_name='lead_social_networks', schema='public')
    op.drop_index(op.f('ix_public_lead_social_networks_lead_id'), table_name='lead_social_networks', schema='public')
    op.drop_table('lead_social_networks', schema='public')
    # ### end Alembic commands ###
