import { useAnalytics } from '../hooks/useAnalytics';
import Card from '../components/ui/Card';
import { PageLoader } from '../components/ui/Spinner';
import PageHeader from '../components/layout/PageHeader';
import LineChart from '../components/charts/LineChart';
import BarChart from '../components/charts/BarChart';
import FunnelChart from '../components/charts/FunnelChart';
// utils used inline below
import { useMemo } from 'react';
import type { DailyReport } from '../lib/api';
import { Download } from 'lucide-react';
import Button from '../components/ui/Button';
import { downloadReport } from '../lib/api';
import { downloadBlob } from '../lib/utils';
import toast from 'react-hot-toast';
import DataTable, { type Column } from '../components/ui/DataTable';
import { motion } from 'framer-motion';
import { pageTransition, staggerContainer, staggerItem, fadeInUp, defaultViewport } from '../lib/motion';

/**
 * The Analytics page visualizes historical performance data.
 * 
 * It aggregates daily reports generated by the backend and displays them using
 * various charts (Funnel, Line, Bar) to help users understand conversion rates,
 * discovery volume, and outreach efficacy over time. Users can also download 
 * raw report data as JSON.
 */
export default function Analytics() {
  const { data: reports, isLoading } = useAnalytics();

  const chartData = useMemo(() => {
    if (!reports?.length) return { line: [], bar: [], funnel: [] };

    const sortedReports = [...reports].sort((a, b) =>
      new Date(a.report_date).getTime() - new Date(b.report_date).getTime()
    );

    const line = sortedReports.map((r: DailyReport) => ({
      date: r.report_date,
      leads_discovered: r.leads_discovered ?? 0,
      emails_sent: r.emails_sent ?? 0,
      emails_opened: r.emails_opened ?? 0,
    }));

    const bar = sortedReports.map((r: DailyReport) => ({
      date: r.report_date,
      qualified: r.leads_qualified ?? 0,
      sent: r.emails_sent ?? 0,
    }));

    // Funnel: aggregate from last 7 reports
    const recent = sortedReports.slice(-7);
    const totals = recent.reduce(
      (acc, r) => ({
        discovered: acc.discovered + (r.leads_discovered ?? 0),
        qualified: acc.qualified + (r.leads_qualified ?? 0),
        personalized: acc.personalized + (r.emails_personalized ?? 0),
        emailed: acc.emailed + (r.emails_sent ?? 0),
        opened: acc.opened + (r.emails_opened ?? 0),
      }),
      { discovered: 0, qualified: 0, personalized: 0, emailed: 0, opened: 0 },
    );

    const funnel = [
      { label: 'Discovered', value: totals.discovered, color: '#111111' },
      { label: 'Qualified', value: totals.qualified, color: '#333333' },
      { label: 'Personalized', value: totals.personalized, color: '#666666' },
      { label: 'Emailed', value: totals.emailed, color: '#999999' },
      { label: 'Opened', value: totals.opened, color: '#CCCCCC' },
    ];

    return { line, bar, funnel };
  }, [reports]);

  const handleDownloadReport = async (date: string) => {
    try {
      const blob = await downloadReport(date);
      downloadBlob(blob, `report_${date}.json`);
      toast.success('Report downloaded');
    } catch {
      toast.error('Download failed');
    }
  };

  const columns: Column<DailyReport>[] = [
    { 
      key: 'report_date', 
      label: 'Date',
      render: (value) => <span className="font-mono">{String(value)}</span>
    },
    { key: 'leads_discovered', label: 'Discovered' },
    { key: 'leads_qualified', label: 'Qualified' },
    { key: 'emails_sent', label: 'Sent' },
    { key: 'emails_opened', label: 'Opened' },
    {
      key: 'actions',
      label: 'Actions',
      render: (_, r) => (
        <Button 
          variant="ghost" 
          size="sm" 
          icon={<Download />} 
          onClick={() => handleDownloadReport(r.report_date)}
        >
          Download
        </Button>
      )
    }
  ];

  if (isLoading) return <PageLoader />;

  return (
    <motion.div className="space-y-6" initial="initial" animate="animate" variants={pageTransition}>
      <PageHeader
        title="Analytics"
        subtitle={`${reports?.length ?? 0} daily reports`}
      />

      {/* Funnel */}
      <motion.div variants={fadeInUp} initial="hidden" whileInView="visible" viewport={defaultViewport}>
      <Card>
        <h3 className="text-xs font-semibold text-secondary uppercase tracking-widest mb-4">Lead Funnel (Last 7 Days)</h3>
        <FunnelChart stages={chartData.funnel} />
      </Card>
      </motion.div>

      {/* Charts Row */}
      <motion.div className="grid grid-cols-1 lg:grid-cols-2 gap-6" variants={staggerContainer} initial="hidden" whileInView="visible" viewport={defaultViewport}>
        <motion.div variants={staggerItem}>
        <Card>
          <h3 className="text-xs font-semibold text-secondary uppercase tracking-widest mb-4">Lead Discovery & Emails</h3>
          <LineChart
            data={chartData.line}
            lines={[
              { dataKey: 'leads_discovered', color: '#111111', label: 'Leads' },
              { dataKey: 'emails_sent', color: '#666666', label: 'Emails Sent' },
              { dataKey: 'emails_opened', color: '#CCCCCC', label: 'Emails Opened' },
            ]}
          />
        </Card>
        </motion.div>

        <motion.div variants={staggerItem}>
        <Card>
          <h3 className="text-xs font-semibold text-secondary uppercase tracking-widest mb-4">Qualification & Outreach</h3>
          <BarChart
            data={chartData.bar}
            bars={[
              { dataKey: 'qualified', color: '#111111', label: 'Qualified' },
              { dataKey: 'sent', color: '#999999', label: 'Sent' },
            ]}
          />
        </Card>
        </motion.div>
      </motion.div>

      {/* Reports Table */}
      <motion.div variants={fadeInUp} initial="hidden" whileInView="visible" viewport={defaultViewport}>
      <Card>
        <h3 className="text-xs font-semibold text-secondary uppercase tracking-widest mb-4">Daily Reports</h3>
        <DataTable
          columns={columns}
          data={reports ?? []}
        />
      </Card>
      </motion.div>
    </motion.div>
  );
}
