/**
 * Use cases — pre-segmented by audience.
 *
 * Each persona block is a structured answer to "who is this for?" — a
 * common AEO query shape. We expose each persona as a HowTo-style block
 * with a short, scannable workflow.
 */
import { Link } from 'react-router-dom';
import { Briefcase, Building2, Code2, Bot, ArrowRight, Sparkles } from 'lucide-react';
import PublicNavbar from '../components/layout/PublicNavbar';
import PublicFooter from '../components/layout/PublicFooter';
import { useSEO } from '../hooks/useSEO';
import JsonLd from '../components/seo/JsonLd';
import { SITE } from '../lib/seo/site';
import { breadcrumbSchema, webPageSchema, itemListSchema } from '../lib/seo/schemas';
import { buildOgImage } from '../lib/seo/og';

const USE_CASES_URL = `${SITE.url}/use-cases`;

const PERSONAS = [
  {
    id: 'freelancer',
    icon: Briefcase,
    title: 'For Freelancers',
    summary:
      'Replace a full SDR job with a weekly Maps-driven pipeline. Spend Monday reviewing leads instead of hunting them.',
    workflow: [
      'Define your ICP — "boutique restaurants in Bengaluru, 4.3+ rating, 200+ reviews".',
      'Run weekly discovery — Cold Scout returns 200 candidates → 30 qualified.',
      'Generate first-draft cold emails personalized from each prospect\'s website.',
      'Edit ~20% by hand for tone; send 30/day from a warmed inbox.',
    ],
  },
  {
    id: 'agency',
    icon: Building2,
    title: 'For Agencies',
    summary:
      'Run multiple ICPs simultaneously, one per client engagement. White-label outreach with priority support on Enterprise.',
    workflow: [
      'Create one pipeline per client with custom ICP rubrics.',
      'Centralize qualification and reporting in a single dashboard.',
      'White-label email templates per brand.',
      'Run weekly performance summaries auto-generated by AI.',
    ],
  },
  {
    id: 'saas',
    icon: Code2,
    title: 'For SaaS Companies',
    summary:
      'Go-to-market team of one. Use Cold Scout to source local-business prospects when your ICP is offline-first SMBs.',
    workflow: [
      'Use Cold Scout when your buyer has a Google Maps presence.',
      'Layer it under a sales engineering script for inbound qualification.',
      'Sync export to Pipedrive/HubSpot via the export-to-CSV flow.',
      'Iterate the qualification prompt against actual close rates.',
    ],
  },
  {
    id: 'agent-builder',
    icon: Bot,
    title: 'For AI Agent Builders',
    summary:
      'Connect Claude, GPT, or Cursor to Cold Scout via the MCP server. Lead generation as a first-class agent capability.',
    workflow: [
      'Sign up for Cold Scout Pro — MCP server is included.',
      'Generate an MCP API key and configure your client.',
      'Agents can now call search_places, qualify_lead, generate_email, send_email.',
      'Build your own outbound automation on top.',
    ],
  },
];

const LD_BREADCRUMB = breadcrumbSchema(
  [
    { name: 'Home', url: `${SITE.url}/` },
    { name: 'Use Cases', url: USE_CASES_URL },
  ],
  USE_CASES_URL,
);

const LD_WEBPAGE = webPageSchema({
  url: USE_CASES_URL,
  name: 'Use Cases — Cold Scout for Freelancers, Agencies, SaaS, AI Agents',
  description:
    'Cold Scout use cases for freelancers, marketing agencies, SaaS go-to-market teams, and AI agent builders.',
});

const LD_ITEMLIST = itemListSchema(
  PERSONAS.map((p) => ({
    url: `${USE_CASES_URL}#${p.id}`,
    name: p.title,
    description: p.summary,
  })),
  USE_CASES_URL,
);

export default function UseCases() {
  useSEO({
    title: 'Use Cases — Cold Scout for Freelancers, Agencies, SaaS, AI Agents',
    description:
      'Cold Scout use cases for freelancers, marketing agencies, SaaS go-to-market teams, and AI agent builders. See exactly how each persona uses the platform.',
    canonical: USE_CASES_URL,
    keywords:
      'AI lead generation use cases, freelancer client acquisition, agency outreach automation, SaaS go-to-market, AI agent lead generation',
    ogImage: buildOgImage({
      title: 'Built for everyone who hunts leads',
      subtitle: 'Freelancers · Agencies · SaaS · AI Agents',
      badge: 'USE CASES',
    }),
  });

  return (
    <div className="bg-black text-white font-sans antialiased">
      <JsonLd data={LD_WEBPAGE} id="webpage-use-cases" />
      <JsonLd data={LD_BREADCRUMB} id="breadcrumb-use-cases" />
      <JsonLd data={LD_ITEMLIST} id="itemlist-use-cases" />
      <PublicNavbar />

      <section className="relative pt-32 pb-12 bg-black">
        <div className="absolute inset-0 noise-overlay opacity-[0.15]" />
        <div className="relative max-w-4xl mx-auto px-6 text-center">
          <div className="inline-flex items-center gap-2 border border-white/10 rounded-full px-4 py-1.5 mb-6 bg-white/[0.03]">
            <Sparkles className="w-3.5 h-3.5 text-white" />
            <span className="text-xs font-medium text-[#B0B0B0]">Use cases</span>
          </div>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tighter text-white leading-[0.95] mb-5">
            Built for everyone<br />who hunts leads.
          </h1>
          <p className="text-lg text-[#B0B0B0] max-w-2xl mx-auto">
            Four ways teams use Cold Scout in production today. Pick the workflow closest to yours.
          </p>
        </div>
      </section>

      <section className="py-12 bg-black">
        <div className="max-w-5xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 gap-6">
          {PERSONAS.map((p) => (
            <article
              key={p.id}
              id={p.id}
              className="border border-white/[0.08] hover:border-white/15 rounded-2xl bg-surface-2 p-7 scroll-mt-32"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-9 h-9 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center">
                  <p.icon className="w-4 h-4 text-white" />
                </div>
                <h2 className="text-lg font-bold tracking-tight text-white">{p.title}</h2>
              </div>
              <p className="text-sm text-[#B0B0B0] leading-relaxed mb-5">{p.summary}</p>
              <ol className="space-y-2.5">
                {p.workflow.map((step, i) => (
                  <li
                    key={step}
                    className="flex items-start gap-3 text-sm text-[#C0C0C0]"
                  >
                    <span className="flex-shrink-0 w-5 h-5 rounded-full bg-white/10 border border-white/10 flex items-center justify-center text-[10px] font-bold text-white mt-0.5">
                      {i + 1}
                    </span>
                    <span>{step}</span>
                  </li>
                ))}
              </ol>
            </article>
          ))}
        </div>
      </section>

      <section className="py-16 bg-surface-1">
        <div className="max-w-3xl mx-auto px-6 text-center">
          <h2 className="text-2xl md:text-3xl font-bold tracking-tighter text-white mb-4">
            Pick your starting point
          </h2>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mt-6">
            <Link
              to="/pricing"
              className="inline-flex items-center gap-2 bg-white text-black px-6 py-3 rounded-full text-sm font-medium hover:bg-gray-200"
            >
              See pricing <ArrowRight className="w-3.5 h-3.5" />
            </Link>
            <a
              href="https://github.com/colddsam/coldscout/releases"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 border border-white/15 text-white px-6 py-3 rounded-full text-sm font-medium hover:bg-white/10"
            >
              Download OSS <ArrowRight className="w-3.5 h-3.5" />
            </a>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
