"""Add state column to leads

Revision ID: 0dfbaa4bb489
Revises: c3f21d9e77b1
Create Date: 2026-03-22 12:20:46.578453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfbaa4bb489'
down_revision: Union[str, None] = 'c3f21d9e77b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_events_outreach_id_fkey', 'email_events', type_='foreignkey')
    op.drop_constraint('email_events_lead_id_fkey', 'email_events', type_='foreignkey')
    op.create_foreign_key(None, 'email_events', 'email_outreach', ['outreach_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'email_events', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('email_outreach_campaign_id_fkey', 'email_outreach', type_='foreignkey')
    op.drop_constraint('email_outreach_lead_id_fkey', 'email_outreach', type_='foreignkey')
    op.create_foreign_key(None, 'email_outreach', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'email_outreach', 'campaigns', ['campaign_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('lead_social_networks', sa.Column('platform', sa.String(length=50), nullable=False, server_default='unknown'))
    op.add_column('lead_social_networks', sa.Column('url', sa.String(), nullable=False, server_default=''))
    op.drop_index('ix_public_lead_social_networks_platform_name', table_name='lead_social_networks')
    op.create_index(op.f('ix_public_lead_social_networks_platform'), 'lead_social_networks', ['platform'], unique=False, schema='public')
    op.drop_constraint('lead_social_networks_lead_id_fkey', 'lead_social_networks', type_='foreignkey')
    op.create_foreign_key(None, 'lead_social_networks', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('lead_social_networks', 'platform_name')
    op.drop_column('lead_social_networks', 'profile_url')
    op.add_column('leads', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('qualification_notes', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('competitor_intel', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('follow_up_stage', sa.Integer(), nullable=True))
    op.drop_column('leads', 'qualification_score')
    op.drop_column('leads', 'web_presence_notes')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.add_column('leads', sa.Column('web_presence_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('qualification_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('leads', 'follow_up_stage')
    op.drop_column('leads', 'competitor_intel')
    op.drop_column('leads', 'qualification_notes')
    op.drop_column('leads', 'ai_score')
    op.drop_column('leads', 'state')
    op.add_column('lead_social_networks', sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lead_social_networks', sa.Column('platform_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lead_social_networks', schema='public', type_='foreignkey')
    op.create_foreign_key('lead_social_networks_lead_id_fkey', 'lead_social_networks', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_lead_social_networks_platform'), table_name='lead_social_networks', schema='public')
    op.create_index('ix_public_lead_social_networks_platform_name', 'lead_social_networks', ['platform_name'], unique=False)
    op.drop_column('lead_social_networks', 'url')
    op.drop_column('lead_social_networks', 'platform')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.create_foreign_key('email_outreach_lead_id_fkey', 'email_outreach', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('email_outreach_campaign_id_fkey', 'email_outreach', 'campaigns', ['campaign_id'], ['id'])
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.create_foreign_key('email_events_lead_id_fkey', 'email_events', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key('email_events_outreach_id_fkey', 'email_events', 'email_outreach', ['outreach_id'], ['id'])
    # ### end Alembic commands ###
