"""v2_features

Revision ID: 1a8edbc23e10
Revises: 4bc63e0465f2
Create Date: 2026-03-04 12:59:03.501281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a8edbc23e10'
down_revision: Union[str, None] = '4bc63e0465f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_locations')
    op.drop_index('ix_email_events_event_type', table_name='email_events')
    op.drop_index('ix_email_events_lead_id', table_name='email_events')
    op.drop_index('ix_email_events_occurred_at', table_name='email_events')
    op.create_index(op.f('ix_public_email_events_event_type'), 'email_events', ['event_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_email_events_lead_id'), 'email_events', ['lead_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_email_events_occurred_at'), 'email_events', ['occurred_at'], unique=False, schema='public')
    op.drop_constraint('email_events_lead_id_fkey', 'email_events', type_='foreignkey')
    op.drop_constraint('email_events_outreach_id_fkey', 'email_events', type_='foreignkey')
    op.create_foreign_key(None, 'email_events', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'email_events', 'email_outreach', ['outreach_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_email_outreach_lead_id', table_name='email_outreach')
    op.drop_index('ix_email_outreach_tracking_token', table_name='email_outreach')
    op.create_index(op.f('ix_public_email_outreach_lead_id'), 'email_outreach', ['lead_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_email_outreach_tracking_token'), 'email_outreach', ['tracking_token'], unique=True, schema='public')
    op.drop_constraint('email_outreach_campaign_id_fkey', 'email_outreach', type_='foreignkey')
    op.drop_constraint('email_outreach_lead_id_fkey', 'email_outreach', type_='foreignkey')
    op.create_foreign_key(None, 'email_outreach', 'campaigns', ['campaign_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'email_outreach', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('lead_social_networks_lead_id_fkey', 'lead_social_networks', type_='foreignkey')
    op.create_foreign_key(None, 'lead_social_networks', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('leads', sa.Column('followup_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('followup_sequence_active', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('reply_classification', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('reply_confidence', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('suggested_reply_draft', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('reply_key_signal', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('website_title', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('website_copyright_year', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('is_mobile_responsive', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('has_online_booking', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('has_ecommerce', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('lead_tier', sa.String(length=50), nullable=True))
    op.alter_column('leads', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_comment='Custom context or remarks about the lead.',
               existing_nullable=True)
    op.drop_index('ix_leads_discovered_at', table_name='leads')
    op.drop_index('ix_leads_place_id', table_name='leads')
    op.drop_index('ix_leads_status', table_name='leads')
    op.create_index(op.f('ix_public_leads_discovered_at'), 'leads', ['discovered_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_leads_place_id'), 'leads', ['place_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_leads_status'), 'leads', ['status'], unique=False, schema='public')
    op.drop_index('ix_search_history_category', table_name='search_history')
    op.drop_index('ix_search_history_city', table_name='search_history')
    op.drop_index('ix_search_history_created_at', table_name='search_history')
    op.create_index(op.f('ix_public_search_history_category'), 'search_history', ['category'], unique=False, schema='public')
    op.create_index(op.f('ix_public_search_history_city'), 'search_history', ['city'], unique=False, schema='public')
    op.create_index(op.f('ix_public_search_history_created_at'), 'search_history', ['created_at'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_search_history_created_at'), table_name='search_history', schema='public')
    op.drop_index(op.f('ix_public_search_history_city'), table_name='search_history', schema='public')
    op.drop_index(op.f('ix_public_search_history_category'), table_name='search_history', schema='public')
    op.create_index('ix_search_history_created_at', 'search_history', ['created_at'], unique=False)
    op.create_index('ix_search_history_city', 'search_history', ['city'], unique=False)
    op.create_index('ix_search_history_category', 'search_history', ['category'], unique=False)
    op.drop_index(op.f('ix_public_leads_status'), table_name='leads', schema='public')
    op.drop_index(op.f('ix_public_leads_place_id'), table_name='leads', schema='public')
    op.drop_index(op.f('ix_public_leads_discovered_at'), table_name='leads', schema='public')
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_index('ix_leads_place_id', 'leads', ['place_id'], unique=True)
    op.create_index('ix_leads_discovered_at', 'leads', ['discovered_at'], unique=False)
    op.alter_column('leads', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_comment='Custom context or remarks about the lead.',
               existing_nullable=True)
    op.drop_column('leads', 'lead_tier')
    op.drop_column('leads', 'has_ecommerce')
    op.drop_column('leads', 'has_online_booking')
    op.drop_column('leads', 'is_mobile_responsive')
    op.drop_column('leads', 'website_copyright_year')
    op.drop_column('leads', 'website_title')
    op.drop_column('leads', 'reply_key_signal')
    op.drop_column('leads', 'suggested_reply_draft')
    op.drop_column('leads', 'reply_confidence')
    op.drop_column('leads', 'reply_classification')
    op.drop_column('leads', 'followup_sequence_active')
    op.drop_column('leads', 'next_followup_at')
    op.drop_column('leads', 'followup_count')
    op.drop_constraint(None, 'lead_social_networks', schema='public', type_='foreignkey')
    op.create_foreign_key('lead_social_networks_lead_id_fkey', 'lead_social_networks', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.create_foreign_key('email_outreach_lead_id_fkey', 'email_outreach', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('email_outreach_campaign_id_fkey', 'email_outreach', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index(op.f('ix_public_email_outreach_tracking_token'), table_name='email_outreach', schema='public')
    op.drop_index(op.f('ix_public_email_outreach_lead_id'), table_name='email_outreach', schema='public')
    op.create_index('ix_email_outreach_tracking_token', 'email_outreach', ['tracking_token'], unique=True)
    op.create_index('ix_email_outreach_lead_id', 'email_outreach', ['lead_id'], unique=False)
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.create_foreign_key('email_events_outreach_id_fkey', 'email_events', 'email_outreach', ['outreach_id'], ['id'])
    op.create_foreign_key('email_events_lead_id_fkey', 'email_events', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_public_email_events_occurred_at'), table_name='email_events', schema='public')
    op.drop_index(op.f('ix_public_email_events_lead_id'), table_name='email_events', schema='public')
    op.drop_index(op.f('ix_public_email_events_event_type'), table_name='email_events', schema='public')
    op.create_index('ix_email_events_occurred_at', 'email_events', ['occurred_at'], unique=False)
    op.create_index('ix_email_events_lead_id', 'email_events', ['lead_id'], unique=False)
    op.create_index('ix_email_events_event_type', 'email_events', ['event_type'], unique=False)
    op.create_table('target_locations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('radius_meters', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='target_locations_pkey')
    )
    # ### end Alembic commands ###
