"""add_event_types_table

Revision ID: 355dc39d47b5
Revises: bda46036c3f6
Create Date: 2026-05-09 12:52:13.186710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '355dc39d47b5'
down_revision: Union[str, None] = 'bda46036c3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_event_types_freelancer_id'), 'event_types', ['freelancer_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_event_types_id'), 'event_types', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_event_types_slug'), 'event_types', ['slug'], unique=False, schema='public')
    op.drop_index('ix_bookings_end_time', table_name='bookings')
    op.drop_index('ix_bookings_freelancer_id', table_name='bookings')
    op.drop_index('ix_bookings_guest_email', table_name='bookings')
    op.drop_index('ix_bookings_id', table_name='bookings')
    op.drop_index('ix_bookings_start_time', table_name='bookings')
    op.create_index(op.f('ix_public_bookings_end_time'), 'bookings', ['end_time'], unique=False, schema='public')
    op.create_index(op.f('ix_public_bookings_freelancer_id'), 'bookings', ['freelancer_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_bookings_guest_email'), 'bookings', ['guest_email'], unique=False, schema='public')
    op.create_index(op.f('ix_public_bookings_id'), 'bookings', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_bookings_start_time'), 'bookings', ['start_time'], unique=False, schema='public')
    op.drop_constraint('bookings_freelancer_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['freelancer_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('business_profiles_user_id_key', 'business_profiles', type_='unique')
    op.drop_index('ix_business_profiles_user_id', table_name='business_profiles')
    op.create_index(op.f('ix_public_business_profiles_id'), 'business_profiles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=True, schema='public')
    op.drop_constraint('business_profiles_user_id_fkey', 'business_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'business_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_index(op.f('ix_public_campaigns_user_id'), 'campaigns', ['user_id'], unique=False, schema='public')
    op.drop_constraint('campaigns_user_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_index(op.f('ix_public_daily_reports_user_id'), 'daily_reports', ['user_id'], unique=False, schema='public')
    op.create_unique_constraint('uq_daily_reports_date_user', 'daily_reports', ['report_date', 'user_id'], schema='public')
    op.drop_constraint('daily_reports_user_id_fkey', 'daily_reports', type_='foreignkey')
    op.create_foreign_key(None, 'daily_reports', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('email_events_outreach_id_fkey', 'email_events', type_='foreignkey')
    op.drop_constraint('email_events_lead_id_fkey', 'email_events', type_='foreignkey')
    op.create_foreign_key(None, 'email_events', 'email_outreach', ['outreach_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'email_events', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_email_outreach_campaign_id', table_name='email_outreach')
    op.create_index(op.f('ix_public_email_outreach_campaign_id'), 'email_outreach', ['campaign_id'], unique=False, schema='public')
    op.drop_constraint('email_outreach_campaign_id_fkey', 'email_outreach', type_='foreignkey')
    op.drop_constraint('email_outreach_lead_id_fkey', 'email_outreach', type_='foreignkey')
    op.create_foreign_key(None, 'email_outreach', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'email_outreach', 'campaigns', ['campaign_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('freelancer_discovery_configs_user_id_key', 'freelancer_discovery_configs', type_='unique')
    op.drop_index('ix_freelancer_discovery_configs_user_id', table_name='freelancer_discovery_configs')
    op.create_index(op.f('ix_public_freelancer_discovery_configs_user_id'), 'freelancer_discovery_configs', ['user_id'], unique=True, schema='public')
    op.drop_constraint('freelancer_discovery_configs_user_id_fkey', 'freelancer_discovery_configs', type_='foreignkey')
    op.create_foreign_key(None, 'freelancer_discovery_configs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_freelancer_job_configs_job_id', table_name='freelancer_job_configs')
    op.drop_index('ix_freelancer_job_configs_user_id', table_name='freelancer_job_configs')
    op.create_index(op.f('ix_public_freelancer_job_configs_id'), 'freelancer_job_configs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_freelancer_job_configs_job_id'), 'freelancer_job_configs', ['job_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_freelancer_job_configs_user_id'), 'freelancer_job_configs', ['user_id'], unique=False, schema='public')
    op.drop_constraint('freelancer_job_configs_user_id_fkey', 'freelancer_job_configs', type_='foreignkey')
    op.create_foreign_key(None, 'freelancer_job_configs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('freelancer_notification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('freelancer_notification_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_freelancer_notif_job_id', table_name='freelancer_notification_configs')
    op.drop_index('ix_freelancer_notif_user_id', table_name='freelancer_notification_configs')
    op.create_index(op.f('ix_public_freelancer_notification_configs_id'), 'freelancer_notification_configs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_freelancer_notification_configs_job_id'), 'freelancer_notification_configs', ['job_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_freelancer_notification_configs_user_id'), 'freelancer_notification_configs', ['user_id'], unique=False, schema='public')
    op.drop_constraint('freelancer_notification_configs_user_id_fkey', 'freelancer_notification_configs', type_='foreignkey')
    op.create_foreign_key(None, 'freelancer_notification_configs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('freelancer_pipeline_configs_user_id_fkey', 'freelancer_pipeline_configs', type_='foreignkey')
    op.create_foreign_key(None, 'freelancer_pipeline_configs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('freelancer_profiles_user_id_key', 'freelancer_profiles', type_='unique')
    op.drop_index('ix_freelancer_profiles_user_id', table_name='freelancer_profiles')
    op.create_index(op.f('ix_public_freelancer_profiles_id'), 'freelancer_profiles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_freelancer_profiles_user_id'), 'freelancer_profiles', ['user_id'], unique=True, schema='public')
    op.drop_constraint('freelancer_profiles_user_id_fkey', 'freelancer_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'freelancer_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('global_job_configs_job_id_key', 'global_job_configs', type_='unique')
    op.drop_index('ix_global_job_configs_job_id', table_name='global_job_configs')
    op.create_index(op.f('ix_public_global_job_configs_id'), 'global_job_configs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_global_job_configs_job_id'), 'global_job_configs', ['job_id'], unique=True, schema='public')
    op.drop_constraint('global_job_configs_updated_by_fkey', 'global_job_configs', type_='foreignkey')
    op.create_foreign_key(None, 'global_job_configs', 'users', ['updated_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint('lead_social_networks_lead_id_fkey', 'lead_social_networks', type_='foreignkey')
    op.create_foreign_key(None, 'lead_social_networks', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('leads', 'is_private_override',
               existing_type=sa.BOOLEAN(),
               comment='If True, the lead will never be published to the public directory, overriding the 30-day window.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('leads', 'source_channel',
               existing_type=sa.VARCHAR(length=50),
               comment='google_places | threads | manual',
               existing_nullable=True,
               existing_server_default=sa.text("'google_places'::character varying"))
    op.alter_column('leads', 'threads_profile_id',
               existing_type=sa.UUID(),
               comment='FK to threads_profiles — set when lead originates from Threads.',
               existing_nullable=True)
    op.drop_index('ix_leads_country', table_name='leads')
    op.drop_index('ix_leads_country_code', table_name='leads')
    op.drop_index('ix_leads_country_region_city', table_name='leads')
    op.drop_index('ix_leads_is_public', table_name='leads')
    op.drop_index('ix_leads_slug', table_name='leads')
    op.drop_index('ix_public_leads_place_id', table_name='leads')
    op.create_index(op.f('ix_public_leads_place_id'), 'leads', ['place_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_leads_country'), 'leads', ['country'], unique=False, schema='public')
    op.create_index(op.f('ix_public_leads_country_code'), 'leads', ['country_code'], unique=False, schema='public')
    op.create_index(op.f('ix_public_leads_is_public'), 'leads', ['is_public'], unique=False, schema='public')
    op.create_index(op.f('ix_public_leads_slug'), 'leads', ['slug'], unique=True, schema='public')
    op.create_index(op.f('ix_public_leads_user_id'), 'leads', ['user_id'], unique=False, schema='public')
    op.create_unique_constraint('uq_leads_place_id_user_id', 'leads', ['place_id', 'user_id'], schema='public')
    op.drop_constraint('leads_user_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_payment_orders_razorpay_order_id', table_name='payment_orders')
    op.drop_index('ix_payment_orders_user_id', table_name='payment_orders')
    op.create_index(op.f('ix_public_payment_orders_razorpay_order_id'), 'payment_orders', ['razorpay_order_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False, schema='public')
    op.drop_constraint('payment_orders_user_id_fkey', 'payment_orders', type_='foreignkey')
    op.create_foreign_key(None, 'payment_orders', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_portfolio_items_user_id', table_name='portfolio_items')
    op.create_index(op.f('ix_public_portfolio_items_id'), 'portfolio_items', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False, schema='public')
    op.drop_constraint('portfolio_items_user_id_fkey', 'portfolio_items', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_items', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_profile_verifications_user_id', table_name='profile_verifications')
    op.create_index(op.f('ix_public_profile_verifications_id'), 'profile_verifications', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_profile_verifications_user_id'), 'profile_verifications', ['user_id'], unique=False, schema='public')
    op.drop_constraint('profile_verifications_user_id_fkey', 'profile_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'profile_verifications', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('push_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('push_subscriptions', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('push_subscriptions_user_id_fkey', 'push_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'push_subscriptions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_search_history_country', table_name='search_history')
    op.drop_index('ix_search_history_country_code', table_name='search_history')
    op.drop_index('ix_search_history_region', table_name='search_history')
    op.drop_index('ix_search_history_sub_area', table_name='search_history')
    op.create_index(op.f('ix_public_search_history_country'), 'search_history', ['country'], unique=False, schema='public')
    op.create_index(op.f('ix_public_search_history_country_code'), 'search_history', ['country_code'], unique=False, schema='public')
    op.create_index(op.f('ix_public_search_history_region'), 'search_history', ['region'], unique=False, schema='public')
    op.create_index(op.f('ix_public_search_history_sub_area'), 'search_history', ['sub_area'], unique=False, schema='public')
    op.create_index(op.f('ix_public_search_history_user_id'), 'search_history', ['user_id'], unique=False, schema='public')
    op.drop_constraint('search_history_user_id_fkey', 'search_history', type_='foreignkey')
    op.create_foreign_key(None, 'search_history', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_public_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True, schema='public')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('threads_auth', 'token_type',
               existing_type=sa.VARCHAR(length=20),
               comment='short_lived | long_lived',
               existing_nullable=True,
               existing_server_default=sa.text("'long_lived'::character varying"))
    op.drop_index('ix_threads_auth_threads_user_id', table_name='threads_auth')
    op.drop_index('ix_threads_auth_user_id', table_name='threads_auth')
    op.create_index(op.f('ix_public_threads_auth_threads_user_id'), 'threads_auth', ['threads_user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_auth_user_id'), 'threads_auth', ['user_id'], unique=False, schema='public')
    op.drop_constraint('threads_auth_user_id_fkey', 'threads_auth', type_='foreignkey')
    op.create_foreign_key(None, 'threads_auth', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('threads_engagements', 'reply_threads_media_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Media ID of our published reply on Threads.',
               existing_nullable=True)
    op.alter_column('threads_engagements', 'engagement_type',
               existing_type=sa.VARCHAR(length=30),
               comment='reply | follow_up_reply',
               existing_nullable=True,
               existing_server_default=sa.text("'reply'::character varying"))
    op.alter_column('threads_engagements', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='pending | sent | failed | replied_back',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('threads_engagements', 'response_text',
               existing_type=sa.TEXT(),
               comment="The lead's reply to our engagement.",
               existing_nullable=True)
    op.drop_index('ix_threads_engagements_status', table_name='threads_engagements')
    op.drop_index('ix_threads_engagements_threads_post_id', table_name='threads_engagements')
    op.drop_index('ix_threads_engagements_threads_profile_id', table_name='threads_engagements')
    op.drop_index('ix_threads_engagements_user_id', table_name='threads_engagements')
    op.create_index(op.f('ix_public_threads_engagements_status'), 'threads_engagements', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_engagements_threads_post_id'), 'threads_engagements', ['threads_post_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_engagements_threads_profile_id'), 'threads_engagements', ['threads_profile_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_engagements_user_id'), 'threads_engagements', ['user_id'], unique=False, schema='public')
    op.drop_constraint('threads_engagements_threads_profile_id_fkey', 'threads_engagements', type_='foreignkey')
    op.drop_constraint('threads_engagements_user_id_fkey', 'threads_engagements', type_='foreignkey')
    op.drop_constraint('threads_engagements_threads_post_id_fkey', 'threads_engagements', type_='foreignkey')
    op.create_foreign_key(None, 'threads_engagements', 'threads_posts', ['threads_post_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'threads_engagements', 'threads_profiles', ['threads_profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'threads_engagements', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('threads_posts', 'threads_media_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique media ID from the Threads API.',
               existing_nullable=False)
    op.alter_column('threads_posts', 'post_type',
               existing_type=sa.VARCHAR(length=20),
               comment='TEXT | IMAGE | VIDEO | CAROUSEL',
               existing_nullable=True,
               existing_server_default=sa.text("'TEXT'::character varying"))
    op.alter_column('threads_posts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the post was originally created on Threads.',
               existing_nullable=True)
    op.alter_column('threads_posts', 'search_keyword',
               existing_type=sa.VARCHAR(length=255),
               comment='The keyword that matched this post during discovery.',
               existing_nullable=True)
    op.drop_index('ix_threads_posts_search_keyword', table_name='threads_posts')
    op.drop_index('ix_threads_posts_threads_media_id', table_name='threads_posts')
    op.drop_index('ix_threads_posts_threads_profile_id', table_name='threads_posts')
    op.drop_constraint('threads_posts_threads_media_id_key', 'threads_posts', type_='unique')
    op.create_index(op.f('ix_public_threads_posts_search_keyword'), 'threads_posts', ['search_keyword'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_posts_threads_media_id'), 'threads_posts', ['threads_media_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_threads_posts_threads_profile_id'), 'threads_posts', ['threads_profile_id'], unique=False, schema='public')
    op.drop_constraint('threads_posts_threads_profile_id_fkey', 'threads_posts', type_='foreignkey')
    op.create_foreign_key(None, 'threads_posts', 'threads_profiles', ['threads_profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('threads_profiles', 'threads_user_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Numeric user ID from the Threads API.',
               existing_nullable=False)
    op.alter_column('threads_profiles', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='@handle on Threads.',
               existing_nullable=True)
    op.alter_column('threads_profiles', 'qualification_status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending | qualified | rejected | engaged | converted',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('threads_profiles', 'discovered_via',
               existing_type=sa.VARCHAR(length=50),
               comment='keyword_search | mention | manual',
               existing_nullable=True,
               existing_server_default=sa.text("'keyword_search'::character varying"))
    op.drop_index('ix_threads_profiles_lead_id', table_name='threads_profiles')
    op.drop_index('ix_threads_profiles_qualification_status', table_name='threads_profiles')
    op.drop_index('ix_threads_profiles_threads_user_id', table_name='threads_profiles')
    op.drop_index('ix_threads_profiles_user_id', table_name='threads_profiles')
    op.drop_index('ix_threads_profiles_username', table_name='threads_profiles')
    op.create_index(op.f('ix_public_threads_profiles_lead_id'), 'threads_profiles', ['lead_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_profiles_qualification_status'), 'threads_profiles', ['qualification_status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_profiles_threads_user_id'), 'threads_profiles', ['threads_user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_profiles_user_id'), 'threads_profiles', ['user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_profiles_username'), 'threads_profiles', ['username'], unique=False, schema='public')
    op.drop_constraint('threads_profiles_user_id_fkey', 'threads_profiles', type_='foreignkey')
    op.drop_constraint('threads_profiles_lead_id_fkey', 'threads_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'threads_profiles', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'threads_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('threads_search_configs', 'keyword',
               existing_type=sa.VARCHAR(length=255),
               comment="Search term, e.g. 'need web developer'.",
               existing_nullable=False)
    op.alter_column('threads_search_configs', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='Business category mapping for this keyword.',
               existing_nullable=True)
    op.alter_column('threads_search_configs', 'search_type',
               existing_type=sa.VARCHAR(length=10),
               comment='TOP | RECENT — Threads search mode.',
               existing_nullable=True,
               existing_server_default=sa.text("'RECENT'::character varying"))
    op.drop_index('ix_threads_search_configs_is_active', table_name='threads_search_configs')
    op.drop_index('ix_threads_search_configs_keyword', table_name='threads_search_configs')
    op.drop_index('ix_threads_search_configs_user_id', table_name='threads_search_configs')
    op.create_index(op.f('ix_public_threads_search_configs_is_active'), 'threads_search_configs', ['is_active'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_search_configs_keyword'), 'threads_search_configs', ['keyword'], unique=False, schema='public')
    op.create_index(op.f('ix_public_threads_search_configs_user_id'), 'threads_search_configs', ['user_id'], unique=False, schema='public')
    op.drop_constraint('threads_search_configs_user_id_fkey', 'threads_search_configs', type_='foreignkey')
    op.create_foreign_key(None, 'threads_search_configs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_index('ix_user_profiles_username', table_name='user_profiles')
    op.drop_constraint('user_profiles_user_id_key', 'user_profiles', type_='unique')
    op.drop_constraint('user_profiles_username_key', 'user_profiles', type_='unique')
    op.create_index(op.f('ix_public_user_profiles_id'), 'user_profiles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_user_profiles_username'), 'user_profiles', ['username'], unique=True, schema='public')
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_index('ix_users_supabase_uid', table_name='users')
    op.create_index(op.f('ix_public_users_supabase_uid'), 'users', ['supabase_uid'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_supabase_uid'), table_name='users', schema='public')
    op.create_index('ix_users_supabase_uid', 'users', ['supabase_uid'], unique=True)
    op.drop_constraint(None, 'user_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_user_profiles_username'), table_name='user_profiles', schema='public')
    op.drop_index(op.f('ix_public_user_profiles_user_id'), table_name='user_profiles', schema='public')
    op.drop_index(op.f('ix_public_user_profiles_id'), table_name='user_profiles', schema='public')
    op.create_unique_constraint('user_profiles_username_key', 'user_profiles', ['username'])
    op.create_unique_constraint('user_profiles_user_id_key', 'user_profiles', ['user_id'])
    op.create_index('ix_user_profiles_username', 'user_profiles', ['username'], unique=True)
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.drop_constraint(None, 'threads_search_configs', schema='public', type_='foreignkey')
    op.create_foreign_key('threads_search_configs_user_id_fkey', 'threads_search_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_threads_search_configs_user_id'), table_name='threads_search_configs', schema='public')
    op.drop_index(op.f('ix_public_threads_search_configs_keyword'), table_name='threads_search_configs', schema='public')
    op.drop_index(op.f('ix_public_threads_search_configs_is_active'), table_name='threads_search_configs', schema='public')
    op.create_index('ix_threads_search_configs_user_id', 'threads_search_configs', ['user_id'], unique=False)
    op.create_index('ix_threads_search_configs_keyword', 'threads_search_configs', ['keyword'], unique=False)
    op.create_index('ix_threads_search_configs_is_active', 'threads_search_configs', ['is_active'], unique=False)
    op.alter_column('threads_search_configs', 'search_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='TOP | RECENT — Threads search mode.',
               existing_nullable=True,
               existing_server_default=sa.text("'RECENT'::character varying"))
    op.alter_column('threads_search_configs', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Business category mapping for this keyword.',
               existing_nullable=True)
    op.alter_column('threads_search_configs', 'keyword',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Search term, e.g. 'need web developer'.",
               existing_nullable=False)
    op.drop_constraint(None, 'threads_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'threads_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('threads_profiles_lead_id_fkey', 'threads_profiles', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('threads_profiles_user_id_fkey', 'threads_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_threads_profiles_username'), table_name='threads_profiles', schema='public')
    op.drop_index(op.f('ix_public_threads_profiles_user_id'), table_name='threads_profiles', schema='public')
    op.drop_index(op.f('ix_public_threads_profiles_threads_user_id'), table_name='threads_profiles', schema='public')
    op.drop_index(op.f('ix_public_threads_profiles_qualification_status'), table_name='threads_profiles', schema='public')
    op.drop_index(op.f('ix_public_threads_profiles_lead_id'), table_name='threads_profiles', schema='public')
    op.create_index('ix_threads_profiles_username', 'threads_profiles', ['username'], unique=False)
    op.create_index('ix_threads_profiles_user_id', 'threads_profiles', ['user_id'], unique=False)
    op.create_index('ix_threads_profiles_threads_user_id', 'threads_profiles', ['threads_user_id'], unique=False)
    op.create_index('ix_threads_profiles_qualification_status', 'threads_profiles', ['qualification_status'], unique=False)
    op.create_index('ix_threads_profiles_lead_id', 'threads_profiles', ['lead_id'], unique=False)
    op.alter_column('threads_profiles', 'discovered_via',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='keyword_search | mention | manual',
               existing_nullable=True,
               existing_server_default=sa.text("'keyword_search'::character varying"))
    op.alter_column('threads_profiles', 'qualification_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pending | qualified | rejected | engaged | converted',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('threads_profiles', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='@handle on Threads.',
               existing_nullable=True)
    op.alter_column('threads_profiles', 'threads_user_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Numeric user ID from the Threads API.',
               existing_nullable=False)
    op.drop_constraint(None, 'threads_posts', schema='public', type_='foreignkey')
    op.create_foreign_key('threads_posts_threads_profile_id_fkey', 'threads_posts', 'threads_profiles', ['threads_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_threads_posts_threads_profile_id'), table_name='threads_posts', schema='public')
    op.drop_index(op.f('ix_public_threads_posts_threads_media_id'), table_name='threads_posts', schema='public')
    op.drop_index(op.f('ix_public_threads_posts_search_keyword'), table_name='threads_posts', schema='public')
    op.create_unique_constraint('threads_posts_threads_media_id_key', 'threads_posts', ['threads_media_id'])
    op.create_index('ix_threads_posts_threads_profile_id', 'threads_posts', ['threads_profile_id'], unique=False)
    op.create_index('ix_threads_posts_threads_media_id', 'threads_posts', ['threads_media_id'], unique=False)
    op.create_index('ix_threads_posts_search_keyword', 'threads_posts', ['search_keyword'], unique=False)
    op.alter_column('threads_posts', 'search_keyword',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='The keyword that matched this post during discovery.',
               existing_nullable=True)
    op.alter_column('threads_posts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the post was originally created on Threads.',
               existing_nullable=True)
    op.alter_column('threads_posts', 'post_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='TEXT | IMAGE | VIDEO | CAROUSEL',
               existing_nullable=True,
               existing_server_default=sa.text("'TEXT'::character varying"))
    op.alter_column('threads_posts', 'threads_media_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique media ID from the Threads API.',
               existing_nullable=False)
    op.drop_constraint(None, 'threads_engagements', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'threads_engagements', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'threads_engagements', schema='public', type_='foreignkey')
    op.create_foreign_key('threads_engagements_threads_post_id_fkey', 'threads_engagements', 'threads_posts', ['threads_post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('threads_engagements_user_id_fkey', 'threads_engagements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('threads_engagements_threads_profile_id_fkey', 'threads_engagements', 'threads_profiles', ['threads_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_threads_engagements_user_id'), table_name='threads_engagements', schema='public')
    op.drop_index(op.f('ix_public_threads_engagements_threads_profile_id'), table_name='threads_engagements', schema='public')
    op.drop_index(op.f('ix_public_threads_engagements_threads_post_id'), table_name='threads_engagements', schema='public')
    op.drop_index(op.f('ix_public_threads_engagements_status'), table_name='threads_engagements', schema='public')
    op.create_index('ix_threads_engagements_user_id', 'threads_engagements', ['user_id'], unique=False)
    op.create_index('ix_threads_engagements_threads_profile_id', 'threads_engagements', ['threads_profile_id'], unique=False)
    op.create_index('ix_threads_engagements_threads_post_id', 'threads_engagements', ['threads_post_id'], unique=False)
    op.create_index('ix_threads_engagements_status', 'threads_engagements', ['status'], unique=False)
    op.alter_column('threads_engagements', 'response_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="The lead's reply to our engagement.",
               existing_nullable=True)
    op.alter_column('threads_engagements', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='pending | sent | failed | replied_back',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('threads_engagements', 'engagement_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='reply | follow_up_reply',
               existing_nullable=True,
               existing_server_default=sa.text("'reply'::character varying"))
    op.alter_column('threads_engagements', 'reply_threads_media_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Media ID of our published reply on Threads.',
               existing_nullable=True)
    op.drop_constraint(None, 'threads_auth', schema='public', type_='foreignkey')
    op.create_foreign_key('threads_auth_user_id_fkey', 'threads_auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_threads_auth_user_id'), table_name='threads_auth', schema='public')
    op.drop_index(op.f('ix_public_threads_auth_threads_user_id'), table_name='threads_auth', schema='public')
    op.create_index('ix_threads_auth_user_id', 'threads_auth', ['user_id'], unique=False)
    op.create_index('ix_threads_auth_threads_user_id', 'threads_auth', ['threads_user_id'], unique=False)
    op.alter_column('threads_auth', 'token_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='short_lived | long_lived',
               existing_nullable=True,
               existing_server_default=sa.text("'long_lived'::character varying"))
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_subscriptions_user_id'), table_name='subscriptions', schema='public')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=True)
    op.drop_constraint(None, 'search_history', schema='public', type_='foreignkey')
    op.create_foreign_key('search_history_user_id_fkey', 'search_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_public_search_history_user_id'), table_name='search_history', schema='public')
    op.drop_index(op.f('ix_public_search_history_sub_area'), table_name='search_history', schema='public')
    op.drop_index(op.f('ix_public_search_history_region'), table_name='search_history', schema='public')
    op.drop_index(op.f('ix_public_search_history_country_code'), table_name='search_history', schema='public')
    op.drop_index(op.f('ix_public_search_history_country'), table_name='search_history', schema='public')
    op.create_index('ix_search_history_sub_area', 'search_history', ['sub_area'], unique=False)
    op.create_index('ix_search_history_region', 'search_history', ['region'], unique=False)
    op.create_index('ix_search_history_country_code', 'search_history', ['country_code'], unique=False)
    op.create_index('ix_search_history_country', 'search_history', ['country'], unique=False)
    op.drop_constraint(None, 'push_subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key('push_subscriptions_user_id_fkey', 'push_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('push_subscriptions', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('push_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'profile_verifications', schema='public', type_='foreignkey')
    op.create_foreign_key('profile_verifications_user_id_fkey', 'profile_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_profile_verifications_user_id'), table_name='profile_verifications', schema='public')
    op.drop_index(op.f('ix_public_profile_verifications_id'), table_name='profile_verifications', schema='public')
    op.create_index('ix_profile_verifications_user_id', 'profile_verifications', ['user_id'], unique=False)
    op.drop_constraint(None, 'portfolio_items', schema='public', type_='foreignkey')
    op.create_foreign_key('portfolio_items_user_id_fkey', 'portfolio_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_portfolio_items_user_id'), table_name='portfolio_items', schema='public')
    op.drop_index(op.f('ix_public_portfolio_items_id'), table_name='portfolio_items', schema='public')
    op.create_index('ix_portfolio_items_user_id', 'portfolio_items', ['user_id'], unique=False)
    op.drop_constraint(None, 'payment_orders', schema='public', type_='foreignkey')
    op.create_foreign_key('payment_orders_user_id_fkey', 'payment_orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_payment_orders_user_id'), table_name='payment_orders', schema='public')
    op.drop_index(op.f('ix_public_payment_orders_razorpay_order_id'), table_name='payment_orders', schema='public')
    op.create_index('ix_payment_orders_user_id', 'payment_orders', ['user_id'], unique=False)
    op.create_index('ix_payment_orders_razorpay_order_id', 'payment_orders', ['razorpay_order_id'], unique=True)
    op.drop_constraint(None, 'notifications', schema='public', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'leads', schema='public', type_='foreignkey')
    op.create_foreign_key('leads_user_id_fkey', 'leads', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_leads_place_id_user_id', 'leads', schema='public', type_='unique')
    op.drop_index(op.f('ix_public_leads_user_id'), table_name='leads', schema='public')
    op.drop_index(op.f('ix_public_leads_slug'), table_name='leads', schema='public')
    op.drop_index(op.f('ix_public_leads_is_public'), table_name='leads', schema='public')
    op.drop_index(op.f('ix_public_leads_country_code'), table_name='leads', schema='public')
    op.drop_index(op.f('ix_public_leads_country'), table_name='leads', schema='public')
    op.drop_index(op.f('ix_public_leads_place_id'), table_name='leads', schema='public')
    op.create_index('ix_public_leads_place_id', 'leads', ['place_id'], unique=True)
    op.create_index('ix_leads_slug', 'leads', ['slug'], unique=True)
    op.create_index('ix_leads_is_public', 'leads', ['is_public'], unique=False)
    op.create_index('ix_leads_country_region_city', 'leads', ['country_code', 'region', 'city'], unique=False)
    op.create_index('ix_leads_country_code', 'leads', ['country_code'], unique=False)
    op.create_index('ix_leads_country', 'leads', ['country'], unique=False)
    op.alter_column('leads', 'threads_profile_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to threads_profiles — set when lead originates from Threads.',
               existing_nullable=True)
    op.alter_column('leads', 'source_channel',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='google_places | threads | manual',
               existing_nullable=True,
               existing_server_default=sa.text("'google_places'::character varying"))
    op.alter_column('leads', 'is_private_override',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If True, the lead will never be published to the public directory, overriding the 30-day window.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'lead_social_networks', schema='public', type_='foreignkey')
    op.create_foreign_key('lead_social_networks_lead_id_fkey', 'lead_social_networks', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'global_job_configs', schema='public', type_='foreignkey')
    op.create_foreign_key('global_job_configs_updated_by_fkey', 'global_job_configs', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_public_global_job_configs_job_id'), table_name='global_job_configs', schema='public')
    op.drop_index(op.f('ix_public_global_job_configs_id'), table_name='global_job_configs', schema='public')
    op.create_index('ix_global_job_configs_job_id', 'global_job_configs', ['job_id'], unique=False)
    op.create_unique_constraint('global_job_configs_job_id_key', 'global_job_configs', ['job_id'])
    op.drop_constraint(None, 'freelancer_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('freelancer_profiles_user_id_fkey', 'freelancer_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_freelancer_profiles_user_id'), table_name='freelancer_profiles', schema='public')
    op.drop_index(op.f('ix_public_freelancer_profiles_id'), table_name='freelancer_profiles', schema='public')
    op.create_index('ix_freelancer_profiles_user_id', 'freelancer_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('freelancer_profiles_user_id_key', 'freelancer_profiles', ['user_id'])
    op.drop_constraint(None, 'freelancer_pipeline_configs', schema='public', type_='foreignkey')
    op.create_foreign_key('freelancer_pipeline_configs_user_id_fkey', 'freelancer_pipeline_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'freelancer_notification_configs', schema='public', type_='foreignkey')
    op.create_foreign_key('freelancer_notification_configs_user_id_fkey', 'freelancer_notification_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_freelancer_notification_configs_user_id'), table_name='freelancer_notification_configs', schema='public')
    op.drop_index(op.f('ix_public_freelancer_notification_configs_job_id'), table_name='freelancer_notification_configs', schema='public')
    op.drop_index(op.f('ix_public_freelancer_notification_configs_id'), table_name='freelancer_notification_configs', schema='public')
    op.create_index('ix_freelancer_notif_user_id', 'freelancer_notification_configs', ['user_id'], unique=False)
    op.create_index('ix_freelancer_notif_job_id', 'freelancer_notification_configs', ['job_id'], unique=False)
    op.alter_column('freelancer_notification_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('freelancer_notification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'freelancer_job_configs', schema='public', type_='foreignkey')
    op.create_foreign_key('freelancer_job_configs_user_id_fkey', 'freelancer_job_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_freelancer_job_configs_user_id'), table_name='freelancer_job_configs', schema='public')
    op.drop_index(op.f('ix_public_freelancer_job_configs_job_id'), table_name='freelancer_job_configs', schema='public')
    op.drop_index(op.f('ix_public_freelancer_job_configs_id'), table_name='freelancer_job_configs', schema='public')
    op.create_index('ix_freelancer_job_configs_user_id', 'freelancer_job_configs', ['user_id'], unique=False)
    op.create_index('ix_freelancer_job_configs_job_id', 'freelancer_job_configs', ['job_id'], unique=False)
    op.drop_constraint(None, 'freelancer_discovery_configs', schema='public', type_='foreignkey')
    op.create_foreign_key('freelancer_discovery_configs_user_id_fkey', 'freelancer_discovery_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_freelancer_discovery_configs_user_id'), table_name='freelancer_discovery_configs', schema='public')
    op.create_index('ix_freelancer_discovery_configs_user_id', 'freelancer_discovery_configs', ['user_id'], unique=False)
    op.create_unique_constraint('freelancer_discovery_configs_user_id_key', 'freelancer_discovery_configs', ['user_id'])
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.create_foreign_key('email_outreach_lead_id_fkey', 'email_outreach', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('email_outreach_campaign_id_fkey', 'email_outreach', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_email_outreach_campaign_id'), table_name='email_outreach', schema='public')
    op.create_index('ix_email_outreach_campaign_id', 'email_outreach', ['campaign_id'], unique=False)
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.create_foreign_key('email_events_lead_id_fkey', 'email_events', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('email_events_outreach_id_fkey', 'email_events', 'email_outreach', ['outreach_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'daily_reports', schema='public', type_='foreignkey')
    op.create_foreign_key('daily_reports_user_id_fkey', 'daily_reports', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_daily_reports_date_user', 'daily_reports', schema='public', type_='unique')
    op.drop_index(op.f('ix_public_daily_reports_user_id'), table_name='daily_reports', schema='public')
    op.drop_constraint(None, 'campaigns', schema='public', type_='foreignkey')
    op.create_foreign_key('campaigns_user_id_fkey', 'campaigns', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_public_campaigns_user_id'), table_name='campaigns', schema='public')
    op.drop_constraint(None, 'business_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('business_profiles_user_id_fkey', 'business_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_business_profiles_user_id'), table_name='business_profiles', schema='public')
    op.drop_index(op.f('ix_public_business_profiles_id'), table_name='business_profiles', schema='public')
    op.create_index('ix_business_profiles_user_id', 'business_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('business_profiles_user_id_key', 'business_profiles', ['user_id'])
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.create_foreign_key('bookings_freelancer_id_fkey', 'bookings', 'users', ['freelancer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_bookings_start_time'), table_name='bookings', schema='public')
    op.drop_index(op.f('ix_public_bookings_id'), table_name='bookings', schema='public')
    op.drop_index(op.f('ix_public_bookings_guest_email'), table_name='bookings', schema='public')
    op.drop_index(op.f('ix_public_bookings_freelancer_id'), table_name='bookings', schema='public')
    op.drop_index(op.f('ix_public_bookings_end_time'), table_name='bookings', schema='public')
    op.create_index('ix_bookings_start_time', 'bookings', ['start_time'], unique=False)
    op.create_index('ix_bookings_id', 'bookings', ['id'], unique=False)
    op.create_index('ix_bookings_guest_email', 'bookings', ['guest_email'], unique=False)
    op.create_index('ix_bookings_freelancer_id', 'bookings', ['freelancer_id'], unique=False)
    op.create_index('ix_bookings_end_time', 'bookings', ['end_time'], unique=False)
    op.drop_index(op.f('ix_public_event_types_slug'), table_name='event_types', schema='public')
    op.drop_index(op.f('ix_public_event_types_id'), table_name='event_types', schema='public')
    op.drop_index(op.f('ix_public_event_types_freelancer_id'), table_name='event_types', schema='public')
    op.drop_table('event_types', schema='public')
    # ### end Alembic commands ###
