"""Add SearchHistory model

Revision ID: 95ce86b637d4
Revises: a5f84f116b9a
Create Date: 2026-02-22 02:18:51.893742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ce86b637d4'
down_revision: Union[str, None] = 'a5f84f116b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_category'), 'search_history', ['category'], unique=False)
    op.create_index(op.f('ix_search_history_city'), 'search_history', ['city'], unique=False)
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.alter_column('email_events', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('email_outreach', 'attachment_names',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="array_to_json(attachment_names)")
    op.alter_column('target_locations', 'categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="array_to_json(categories)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_locations', 'categories',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('email_outreach', 'attachment_names',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('email_events', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_city'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_category'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
