"""Initial schema

Revision ID: a5f84f116b9a
Revises: 
Create Date: 2026-02-21 18:07:15.036511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5f84f116b9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('emails_opened', sa.Integer(), nullable=True),
    sa.Column('links_clicked', sa.Integer(), nullable=True),
    sa.Column('replies_received', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('leads_discovered', sa.Integer(), nullable=True),
    sa.Column('leads_qualified', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('emails_opened', sa.Integer(), nullable=True),
    sa.Column('links_clicked', sa.Integer(), nullable=True),
    sa.Column('replies_received', sa.Integer(), nullable=True),
    sa.Column('new_conversions', sa.Integer(), nullable=True),
    sa.Column('report_file_path', sa.String(), nullable=True),
    sa.Column('email_sent_to', sa.String(length=255), nullable=True),
    sa.Column('pipeline_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_status', sa.String(length=50), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('google_maps_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('qualification_score', sa.Integer(), nullable=True),
    sa.Column('has_website', sa.Boolean(), nullable=True),
    sa.Column('has_social_media', sa.Boolean(), nullable=True),
    sa.Column('web_presence_notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_places_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_discovered_at'), 'leads', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_leads_place_id'), 'leads', ['place_id'], unique=True)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('target_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('radius_meters', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_outreach',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('tracking_token', sa.String(length=255), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.Column('attachment_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounce_reason', sa.Text(), nullable=True),
    sa.Column('brevo_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_outreach_lead_id'), 'email_outreach', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_outreach_tracking_token'), 'email_outreach', ['tracking_token'], unique=True)
    op.create_table('email_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('outreach_id', sa.UUID(), nullable=True),
    sa.Column('tracking_token', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('url_clicked', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['outreach_id'], ['email_outreach.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_event_type'), 'email_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_events_lead_id'), 'email_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_events_occurred_at'), 'email_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_events_occurred_at'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_lead_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_type'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_email_outreach_tracking_token'), table_name='email_outreach')
    op.drop_index(op.f('ix_email_outreach_lead_id'), table_name='email_outreach')
    op.drop_table('email_outreach')
    op.drop_table('target_locations')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_place_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_discovered_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('daily_reports')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
