"""add_native_scheduling

Revision ID: b035ac23c181
Revises: u5v6w7x8y9z0
Create Date: 2026-05-08 23:56:32.311575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b035ac23c181'
down_revision: Union[str, None] = 'u5v6w7x8y9z0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_notes', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
    sa.Column('booking_type', sa.String(length=50), nullable=False, server_default='standard'),
    sa.Column('meeting_link', sa.String(length=1000), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_end_time'), 'bookings', ['end_time'], unique=False)
    op.create_index(op.f('ix_bookings_freelancer_id'), 'bookings', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_bookings_guest_email'), 'bookings', ['guest_email'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    
    op.add_column('freelancer_profiles', sa.Column('scheduling_preferences', sa.JSON(), nullable=True))
    op.add_column('freelancer_profiles', sa.Column('booking_confirmation_mode', sa.String(length=50), nullable=False, server_default='auto'))
    op.add_column('freelancer_profiles', sa.Column('google_calendar_credentials', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancer_profiles', 'google_calendar_credentials')
    op.drop_column('freelancer_profiles', 'booking_confirmation_mode')
    op.drop_column('freelancer_profiles', 'scheduling_preferences')
    
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_freelancer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_time'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
