"""v2_features

Revision ID: fabaa4a4c84e
Revises: 1a8edbc23e10
Create Date: 2026-03-04 13:03:06.382906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fabaa4a4c84e'
down_revision: Union[str, None] = '1a8edbc23e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('performance_score', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_prompt_configs_prompt_type'), 'prompt_configs', ['prompt_type'], unique=False, schema='public')
    op.drop_constraint('email_events_outreach_id_fkey', 'email_events', type_='foreignkey')
    op.drop_constraint('email_events_lead_id_fkey', 'email_events', type_='foreignkey')
    op.create_foreign_key(None, 'email_events', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'email_events', 'email_outreach', ['outreach_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('email_outreach_campaign_id_fkey', 'email_outreach', type_='foreignkey')
    op.drop_constraint('email_outreach_lead_id_fkey', 'email_outreach', type_='foreignkey')
    op.create_foreign_key(None, 'email_outreach', 'campaigns', ['campaign_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'email_outreach', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('lead_social_networks_lead_id_fkey', 'lead_social_networks', type_='foreignkey')
    op.create_foreign_key(None, 'lead_social_networks', 'leads', ['lead_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_social_networks', schema='public', type_='foreignkey')
    op.create_foreign_key('lead_social_networks_lead_id_fkey', 'lead_social_networks', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_outreach', schema='public', type_='foreignkey')
    op.create_foreign_key('email_outreach_lead_id_fkey', 'email_outreach', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('email_outreach_campaign_id_fkey', 'email_outreach', 'campaigns', ['campaign_id'], ['id'])
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'email_events', schema='public', type_='foreignkey')
    op.create_foreign_key('email_events_lead_id_fkey', 'email_events', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key('email_events_outreach_id_fkey', 'email_events', 'email_outreach', ['outreach_id'], ['id'])
    op.drop_index(op.f('ix_public_prompt_configs_prompt_type'), table_name='prompt_configs', schema='public')
    op.drop_table('prompt_configs', schema='public')
    # ### end Alembic commands ###
