"""Add demo website generation fields to leads

Revision ID: h2i3j4k5l6m7
Revises: g1h2i3j4k5l6
Create Date: 2026-04-05

Adds generated_demo_html, demo_site_status, demo_generated_at, demo_view_count
to the leads table for the AI-generated demo website feature targeting
no-website leads.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'h2i3j4k5l6m7'
down_revision = 'g1h2i3j4k5l6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('leads', sa.Column(
        'generated_demo_html', sa.Text(), nullable=True,
        comment='Raw interactive HTML generated by Gemini for no-website leads.',
    ))
    op.add_column('leads', sa.Column(
        'demo_site_status', sa.String(20), nullable=False,
        server_default='not_applicable',
        comment='not_applicable | pending | generating | generated | failed',
    ))
    op.add_column('leads', sa.Column(
        'demo_generated_at', sa.DateTime(timezone=True), nullable=True,
        comment='Timestamp when demo HTML was successfully generated.',
    ))
    op.add_column('leads', sa.Column(
        'demo_view_count', sa.Integer(), nullable=False,
        server_default='0',
        comment='Number of times the demo page was viewed by the recipient.',
    ))


def downgrade() -> None:
    op.drop_column('leads', 'demo_view_count')
    op.drop_column('leads', 'demo_generated_at')
    op.drop_column('leads', 'demo_site_status')
    op.drop_column('leads', 'generated_demo_html')
